/**
 * This code was generated by Builder.io.
 */
import React from "react";
import WelcomeSection from "./WelcomeSection";
import LoginForm from "./LoginForm";

const LoginPage: React.FC = () => {
  return (
    <main className="flex overflow-hidden flex-col border border-black border-solid bg-black bg-opacity-0 shadow-[0px_4px_4px_rgba(0,0,0,0.25)]">
      <div className="w-full bg-black bg-opacity-0 max-md:max-w-full">
        <div className="flex gap-5 max-md:flex-col">
          <WelcomeSection />
          <LoginForm />
        </div>
      </div>
    </main>
  );
};

export default LoginPage;
