/**
 * This code was generated by Builder.io.
 */
import React from "react";

const WelcomeSection: React.FC = () => {
  return (
    <section className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
      <div className="flex z-10 flex-col grow w-full font-semibold text-center bg-black bg-opacity-0 max-md:-mr-1.5 max-md:max-w-full">
        <div className="flex relative flex-col justify-center items-start px-20 py-64 w-full min-h-[677px] max-md:py-24 max-md:pl-5 max-md:max-w-full">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/a3a6b812b34752e72596004189492c1afa053a6ca095fc5773ad18a614d62670?placeholderIfAbsent=true&apiKey=522f082a491d4bc58a4fc1aa5c676416"
            alt=""
            className="object-cover absolute inset-0 size-full"
          />
          <div className="flex relative flex-col items-start px-16 py-6 mb-0 bg-black bg-opacity-0 max-md:px-5 max-md:mb-2.5 max-md:max-w-full">
            <h1 className="text-3xl text-gray-900">
              Welcome to Hospital <br /> Login
            </h1>
            <p className="mt-4 text-xs text-zinc-400">
              Securely access your hospital's digital services with our user-{" "}
              <br /> friendly login experience.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default WelcomeSection;
